# Generated by Django 2.2.26 on 2023-05-13 21:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('maintenance_date', models.DateField(default=datetime.datetime(2023, 5, 13, 21, 57, 41, 526892))),
                ('mach', models.CharField(choices=[('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Switch', 'Switch'), ('Serveur', 'Serveur')], default='PC', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99)])),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
            ],
        ),
    ]
