# Generated by Django 4.2.1 on 2023-05-15 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0003_auto_20230513_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 18, 39, 29, 740724)),
        ),
    ]
