# Generated by Django 4.2.1 on 2023-05-21 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0006_alter_machine_mach_alter_machine_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Windows'), ('Serveur', 'Serveur'), ('Switch', 'Switch'), ('Mac', 'Mac - MacOS')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 12, 35, 53, 966022)),
        ),
    ]
