# Generated by Django 2.2.26 on 2023-05-24 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0013_alter_machine_mach_alter_machine_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 8, 0, 22, 801777)),
        ),
    ]
