# Generated by Django 2.2.26 on 2023-05-24 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0014_auto_20230524_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 8, 28, 12, 985997)),
        ),
    ]
