# Generated by Django 2.2.26 on 2023-05-24 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0015_auto_20230524_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 9, 1, 40, 192789)),
        ),
    ]
