# Generated by Django 2.2.26 on 2023-05-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0016_auto_20230524_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Switch', 'Switch'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 25, 8, 28, 19, 105745)),
        ),
    ]
