# Generated by Django 2.2.26 on 2023-05-25 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0017_auto_20230525_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 25, 9, 49, 43, 290292)),
        ),
    ]
