# Generated by Django 4.2.1 on 2023-05-28 10:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0019_alter_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=32, unique=True)),
                ('addresse_ip', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 12, 25, 25, 392117)),
        ),
    ]
