# Generated by Django 4.2.1 on 2023-05-28 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0020_reseau_alter_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('Serveur', 'Serveur'), ('Switch', 'Switch'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 12, 50, 49, 680785)),
        ),
    ]
