# Generated by Django 4.2.1 on 2023-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0023_alter_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
    ]
