# Generated by Django 4.2.1 on 2023-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0029_personnel_machine_id_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
