# Generated by Django 4.2.1 on 2023-05-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0030_alter_machine_mach'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='reseau_assoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projetApp.reseau'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('PC', 'PC - Windows'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
