# Generated by Django 4.2.1 on 2023-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0031_machine_reseau_assoc_alter_machine_etat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='machine_id',
            new_name='machine_assoc',
        ),
        migrations.AddField(
            model_name='personnel',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Windows'), ('Switch', 'Switch'), ('Mac', 'Mac - MacOS'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
    ]
