# Generated by Django 4.2.1 on 2023-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0032_rename_machine_id_personnel_machine_assoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
