# Generated by Django 4.2.1 on 2023-05-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0034_alter_machine_etat_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Routeur', 'Routeur'), ('PC', 'PC - Windows'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
