# Generated by Django 4.2.1 on 2023-05-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0035_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('Routeur', 'Routeur'), ('Switch', 'Switch'), ('Serveur', 'Serveur'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='machine_assoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projetApp.machine'),
        ),
    ]
