# Generated by Django 4.2.1 on 2023-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0036_alter_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseau',
            name='machine_assoc',
            field=models.ManyToManyField(to='projetApp.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('Serveur', 'Serveur'), ('Switch', 'Switch'), ('PC', 'PC - Windows'), ('Routeur', 'Routeur')], default='PC', max_length=32),
        ),
    ]
