# Generated by Django 4.2.1 on 2023-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0038_alter_machine_etat_alter_machine_mach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseau',
            name='machine_assoc',
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Windows'), ('Routeur', 'Routeur'), ('Switch', 'Switch'), ('Mac', 'Mac - MacOS'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
    ]
