# Generated by Django 4.2.1 on 2023-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0039_remove_reseau_machine_assoc_alter_machine_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Routeur', 'Routeur'), ('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
    ]
