# Generated by Django 4.2.1 on 2023-05-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0040_alter_machine_mach'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='personnel_assoc',
            field=models.ForeignKey(blank=True, default=1111111111111, on_delete=django.db.models.deletion.CASCADE, to='projetApp.personnel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Windows'), ('Switch', 'Switch'), ('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('Routeur', 'Routeur')], default='PC', max_length=32),
        ),
    ]
