# Generated by Django 4.2.1 on 2023-05-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0041_machine_personnel_assoc_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Routeur', 'Routeur'), ('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='personnel_assoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projetApp.personnel'),
        ),
    ]
