# Generated by Django 4.2.1 on 2023-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0042_alter_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Routeur', 'Routeur'), ('Serveur', 'Serveur'), ('PC', 'PC - Windows'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
