# Generated by Django 4.2.1 on 2023-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0043_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Routeur', 'Routeur'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS')], default='PC', max_length=32),
        ),
    ]
