# Generated by Django 4.2.1 on 2023-06-07 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0045_alter_machine_mach_alter_machine_personnel_assoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='adresse_ip',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('PC', 'PC - Windows'), ('Switch', 'Switch'), ('Routeur', 'Routeur'), ('Mac', 'Mac - MacOS')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='masque',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='personnel_assoc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projetApp.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reseau_assoc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projetApp.reseau'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='machine_assoc',
            field=models.ManyToManyField(blank=True, default='Aucune Machine', to='projetApp.machine'),
        ),
    ]
