# Generated by Django 4.2.1 on 2023-06-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0046_alter_machine_adresse_ip_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Routeur', 'Routeur'), ('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('PC', 'PC - Windows')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='personnel_assoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetApp.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reseau_assoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetApp.reseau'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='machine_assoc',
            field=models.ManyToManyField(blank=True, to='projetApp.machine'),
        ),
    ]
