# Generated by Django 4.2.1 on 2023-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0048_alter_machine_mach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='machine_assoc',
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Mac', 'Mac - MacOS'), ('Switch', 'Switch'), ('Routeur', 'Routeur'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur')], default='PC', max_length=32),
        ),
    ]
