# Generated by Django 4.2.1 on 2023-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0049_remove_personnel_machine_assoc_alter_machine_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Routeur', 'Routeur'), ('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('PC', 'PC - Windows'), ('Switch', 'Switch')], default='PC', max_length=32),
        ),
    ]
