# Generated by Django 4.2.1 on 2023-06-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetApp', '0050_alter_machine_mach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('Switch', 'Switch'), ('PC', 'PC - Windows'), ('Serveur', 'Serveur'), ('Mac', 'Mac - MacOS'), ('Routeur', 'Routeur')], default='PC', max_length=32),
        ),
    ]
